api-version: 1.16
authors:
  - eloo95
commands:
  amechanics:
    aliases:
      - amech
  mechanics:
    aliases:
      - mech
  es:
main: dev.eloo.mechanics.Mechanics
name: Mechanics
depend:
  - Vault
  - InventoryMenuManager
  - PluginUtils
softdepend:
  - GriefPrevention
  - HolographicDisplays
version: ${project.version}
load: STARTUP